services:
  portfolio:
    image: nginx:stable-alpine
    container_name: portfolio
    read_only: true
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.portfolio.rule=Host(`www.jessekaufman.com`) || Host(`jessekaufman.com`)
      - traefik.http.routers.portfolio.entrypoints=https
      - traefik.http.routers.portfolio.tls=true
      - traefik.http.routers.portfolio.middlewares=public@file
    networks:
      - proxy
    volumes:
      - ./live/public:/var/www/html:ro
      - ./live/config:/etc/nginx/conf.d:rw
      - ./live/logs:/var/log/nginx:rw
    user: ${PUID}:${PGID}
    # healthcheck:
    #   test: curl -f http://localhost:80 --insecure -s
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    tmpfs:
      - /tmp:rw,noexec,nosuid,uid=${PUID},gid=${PGID}
      - /run:rw,noexec,nosuid,uid=${PUID},gid=${PGID}
      - /var/cache/nginx:rw,noexec,nosuid,uid=${PUID},gid=${PGID}
    deploy:
      resources:
        limits:
          cpus: "2"
          pids: 500
          memory: 200M
    restart: always
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
