name: Deploy Hugo Site

on:
  push:
    branches:
      - main # Trigger deploy on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.145.0" # Specify the Hugo version
          extended: true # Enable Hugo extended version

      - name: Test building site
        run: |
          cd hugo  # Navigate to the hugo directory
          git submodule update --init --recursive
          hugo    # Build the site (output goes to hugo/public)

      - name: Trigger deployment via webhook
        run: |
          curl -X POST https://apis.lloydnet.org/actions/api/v1/portfolio \
          -H "Authorization: Bearer ${{ secrets.API_SECRET }}" \
          -H "Content-Type: application/json" \
          -d '{"message": "Deployment triggered by GitHub Actions"}'
